language: generic
sudo: required
services: 
  - docker

before_install: 
 - docker build -t momadison/docker-angular -f Dockerfile.dev .

script:
  - docker run -e CI=true momadison/docker-angular ng test --watch=false