#Get base app
FROM node:12-slim

#Set a working directory
WORKDIR '/app'

#Copy package.json before npm install.  Do not copy all files or 
#npm install will have to run again in the container on every change
COPY package.json .
RUN npm install

#install angular cli
RUN npm install -g @angular/cli

#kind of unneccesary with docker compose since it maps volumes
COPY . .

#from puppeteer to get chrome working in container with test
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

#installs chrome
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
# RUN apt-get update && apt-get install -y google-chrome-stable
# ENV CHROME_BIN /usr/bin/google-chrome-stable


#Run start command
CMD ["ng","serve", "--host","0.0.0.0"]